import { Product, Category } from '@/types';

export const categories: Category[] = [
  { id: '1', name: 'Electronics', slug: 'electronics', image: '/categories/electronics.jpg' },
  { id: '2', name: 'Fashion', slug: 'fashion', image: '/categories/fashion.jpg' },
  { id: '3', name: 'Home & Kitchen', slug: 'home-kitchen', image: '/categories/home.jpg' },
  { id: '4', name: 'Books', slug: 'books', image: '/categories/books.jpg' },
  { id: '5', name: 'Sports', slug: 'sports', image: '/categories/sports.jpg' },
  { id: '6', name: 'Beauty', slug: 'beauty', image: '/categories/beauty.jpg' },
];

export const products: Product[] = [
  {
    id: '1',
    name: 'Wireless Bluetooth Headphones',
    description: 'Premium noise-cancelling headphones with 30-hour battery life and crystal-clear sound quality.',
    price: 2999,
    originalPrice: 4999,
    discount: 40,
    images: [
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800',
      'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=800',
    ],
    category: 'electronics',
    brand: 'SoundMax',
    rating: 4.5,
    reviews: 1245,
    inStock: true,
    specifications: {
      'Battery Life': '30 hours',
      'Connectivity': 'Bluetooth 5.0',
      'Weight': '250g',
      'Color': 'Black',
    },
    offers: ['10% off on SBI Cards', 'Free shipping', '1 year warranty'],
  },
  {
    id: '2',
    name: 'Smart Watch Pro',
    description: 'Feature-rich smartwatch with heart rate monitor, GPS, and 7-day battery life.',
    price: 8999,
    originalPrice: 12999,
    discount: 31,
    images: [
      'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800',
      'https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=800',
    ],
    category: 'electronics',
    brand: 'TechWear',
    rating: 4.7,
    reviews: 892,
    inStock: true,
    specifications: {
      'Display': '1.4" AMOLED',
      'Battery': '7 days',
      'Water Resistance': '5 ATM',
      'Compatibility': 'iOS & Android',
    },
    offers: ['Exchange offer available', 'No Cost EMI'],
  },
  {
    id: '3',
    name: 'Cotton T-Shirt',
    description: 'Comfortable 100% cotton t-shirt, perfect for everyday wear. Available in multiple colors.',
    price: 599,
    originalPrice: 999,
    discount: 40,
    images: [
      'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800',
      'https://images.unsplash.com/photo-1503341504253-dff4815485f1?w=800',
    ],
    category: 'fashion',
    brand: 'StyleCo',
    rating: 4.3,
    reviews: 567,
    inStock: true,
    specifications: {
      'Material': '100% Cotton',
      'Fit': 'Regular',
      'Care': 'Machine Wash',
      'Sizes': 'S, M, L, XL',
    },
    offers: ['Buy 2 Get 1 Free', 'Free shipping'],
  },
  {
    id: '4',
    name: 'Coffee Maker',
    description: 'Programmable coffee maker with 12-cup capacity and auto-shutoff feature.',
    price: 3499,
    originalPrice: 4999,
    discount: 30,
    images: [
      'https://images.unsplash.com/photo-1517487881594-2787fef5ebf7?w=800',
      'https://images.unsplash.com/photo-1497935586351-b67a49e012bf?w=800',
    ],
    category: 'home-kitchen',
    brand: 'BrewMaster',
    rating: 4.6,
    reviews: 432,
    inStock: true,
    specifications: {
      'Capacity': '12 cups',
      'Material': 'Stainless Steel',
      'Warranty': '2 years',
      'Power': '1000W',
    },
    offers: ['Free coffee samples', 'Installation support'],
  },
  {
    id: '5',
    name: 'Running Shoes',
    description: 'Lightweight running shoes with cushioned sole and breathable mesh upper.',
    price: 4499,
    originalPrice: 6999,
    discount: 36,
    images: [
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800',
      'https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=800',
    ],
    category: 'sports',
    brand: 'RunFast',
    rating: 4.4,
    reviews: 789,
    inStock: true,
    specifications: {
      'Material': 'Mesh & Synthetic',
      'Sole': 'Rubber',
      'Sizes': '6-12 UK',
      'Weight': '280g',
    },
    offers: ['30-day return', 'Free size exchange'],
  },
  {
    id: '6',
    name: 'Skincare Set',
    description: 'Complete skincare routine with cleanser, toner, and moisturizer. Suitable for all skin types.',
    price: 1999,
    originalPrice: 2999,
    discount: 33,
    images: [
      'https://images.unsplash.com/photo-1556229010-6c3f2c9ca5f8?w=800',
      'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=800',
    ],
    category: 'beauty',
    brand: 'GlowUp',
    rating: 4.5,
    reviews: 654,
    inStock: true,
    specifications: {
      'Volume': '150ml each',
      'Skin Type': 'All',
      'Paraben Free': 'Yes',
      'Cruelty Free': 'Yes',
    },
    offers: ['Buy 1 Get 1 50% off', 'Free consultation'],
  },
  {
    id: '7',
    name: 'Laptop Stand',
    description: 'Ergonomic aluminum laptop stand with adjustable height and ventilation.',
    price: 1299,
    originalPrice: 1999,
    discount: 35,
    images: [
      'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=800',
      'https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=800',
    ],
    category: 'electronics',
    brand: 'ErgoDesk',
    rating: 4.6,
    reviews: 321,
    inStock: true,
    specifications: {
      'Material': 'Aluminum',
      'Weight': '800g',
      'Max Load': '10kg',
      'Adjustable': 'Yes',
    },
    offers: ['Free shipping', '2 year warranty'],
  },
  {
    id: '8',
    name: 'Wireless Mouse',
    description: 'Ergonomic wireless mouse with 2.4GHz connectivity and 18-month battery life.',
    price: 799,
    originalPrice: 1299,
    discount: 38,
    images: [
      'https://images.unsplash.com/photo-1527814050087-3793815479db?w=800',
      'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=800',
    ],
    category: 'electronics',
    brand: 'ClickTech',
    rating: 4.4,
    reviews: 987,
    inStock: true,
    specifications: {
      'Connectivity': '2.4GHz Wireless',
      'Battery': '18 months',
      'DPI': '1600',
      'Buttons': '3',
    },
    offers: ['No Cost EMI', 'Free mouse pad'],
  },
];

